version: '3'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '1234:1234'
    expose:
      - '1234'
    volumes:
      - .:/root
  production:
    build: .
    ports:
      - '1234:80'
